### ISSUE TITLE
sigstore 0.6.3 doesn't work with cryptography 38.0.1

### ISSUE THREAD

**Issue by ambv** [sigstore/sigstore-python#204]
Installed in an empty virtualenv with default dependencies.

I'm trying to use it with [add-to-pydotorg.py](https://github.com/python/release-tools/blob/master/add-to-pydotorg.py). It gives me the link to follow, I log in with Github, get the verification code, paste the verification code back, and get...

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/psf-users/ambv/release-tools/lib/python3.8/site-packages/sigstore/__main__.py", line 22, in <module>
    main()
  File "/home/psf-users/ambv/release-tools/lib/python3.8/site-packages/sigstore/_cli.py", line 257, in main
    _sign(args)
  File "/home/psf-users/ambv/release-tools/lib/python3.8/site-packages/sigstore/_cli.py", line 382, in _sign
    result = signer.sign(
  File "/home/psf-users/ambv/release-tools/lib/python3.8/site-packages/sigstore/_sign.py", line 101, in sign
    verify_sct(
  File "/home/psf-users/ambv/release-tools/lib/python3.8/site-packages/sigstore/_internal/sct.py", line 279, in verify_sct
    hash_algorithm, signature_algorithm, signature = _sct_properties(sct, raw_sct)
  File "/home/psf-users/ambv/release-tools/lib/python3.8/site-packages/sigstore/_internal/sct.py", line 82, in _sct_properties
    sct.hash_algorithm,  # type: ignore[attr-defined]
AttributeError: 'builtins.Sct' object has no attribute 'hash_algorithm'
```

There is indeed no `hash_algorithm` on the object. There is `signature_hash_algorithm` but that's not it. This seems to be related to compatibility with `cryptography` 38.0.1 because downgrading it to 37.0.4 makes the entire workflow pass successfully. 

I'm not sure whether this is at all related to #84 or #142 or #199 but I'm tagging them all so you can figure it out.

**Comment by woodruffw** [comment]
Thanks for reporting! Yeah, this was caused by some (intentional) breakage in cryptography's APIs that #199 subsequently addressed.

We need to perform a new point release here; I'll use this issue to track it.

**Comment by woodruffw** [comment]
Cut as `0.6.4`. Should be on PyPI shortly.

**Comment by woodruffw** [comment]
Published on PyPI, and the locked install is also now updated. Please don't hesitate to let us know if there are other issues!

**Comment by di** [comment]
Thanks @ambv!
