### ISSUE TITLE
calling Signer.production() raises KeyError for tuf targets metadata

### ISSUE THREAD

**Issue by lukpueh** [sigstore/sigstore-python#529]
**Description**

```python
$ python
>>> from sigstore.sign import Signer
>>> Signer.production()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[SNIP]/sigstore/sign.py", line 104, in production
    rekor = RekorClient.production(updater)
  File "[SNIP]/sigstore/_internal/rekor/client.py", line 283, in production
    rekor_key = updater.get_rekor_key()
  File "[SNIP]/sigstore/_internal/tuf.py", line 174, in get_rekor_key
    keys = self._get("Rekor", ["Active"])
  File "[SNIP]/sigstore/_internal/tuf.py", line 149, in _get
    custom = target_info.unrecognized_fields["custom"]["sigstore"]
KeyError: 'custom'
```

**Version**
```
$ python --version
Python 3.10.9
```

```
$ pip freeze
appdirs==1.4.4
asn1crypto==1.5.1
astroid==2.14.2
bandit==1.7.4
betterproto==2.0.0b5
black==23.1.0
blessed==1.20.0
bpython==0.24
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.0.1
click==8.1.3
colorama==0.4.6
coverage==7.2.1
cryptography==39.0.1
curtsies==0.4.1
cwcwidth==0.1.8
dill==0.3.6
distlib==0.3.6
filelock==3.9.0
gitdb==4.0.10
GitPython==3.1.31
greenlet==2.0.2
grpclib==0.4.3
h2==4.1.0
hpack==4.0.0
hyperframe==6.0.1
idna==3.4
importlib-resources==5.12.0
isort==5.12.0
lazy-object-proxy==1.9.0
mccabe==0.7.0
multidict==6.0.4
mypy==1.0.1
mypy-extensions==1.0.0
packaging==23.0
pathspec==0.11.0
pbr==5.11.1
platformdirs==3.0.0
pluggy==1.0.0
pycparser==2.21
pydantic==1.10.5
Pygments==2.14.0
PyJWT==2.6.0
PyKCS11==1.5.11
pylint==2.16.2
PyNaCl==1.5.0
pyOpenSSL==23.0.0
pyproject_api==1.5.0
PySPX==0.5.0
python-dateutil==2.8.2
pyxdg==0.28
PyYAML==6.0
requests==2.28.2
securesystemslib==0.26.0
sigstore==1.1.0
sigstore-protobuf-specs==0.1.0
six==1.16.0
smmap==5.0.0
stevedore==5.0.0
tomli==2.0.1
tomlkit==0.11.6
tox==4.4.6
tuf==2.1.0
typing_extensions==4.5.0
urllib3==1.26.14
virtualenv==20.19.0
wcwidth==0.2.6
wrapt==1.14.1
```

**Comment by jku** [comment]
I think will and di fixed this already in 1.1.1: #522

**Comment by lukpueh** [comment]
Thanks for the quick reply! I can confirm that a re-install fixed this.
