### ISSUE TITLE
Fulcio certificate chain should be opened as bytes in verify command

### ISSUE THREAD

**Issue by mayaCostantini** [sigstore/sigstore-python#795]
**Description**

When passing a certificate chain as a PEM file to the `sigstore verify` command, I get the following error:

```
Traceback (most recent call last):
  File "/home/mcostant/Documents/Repositories/RedHat/Ansible_Sigstore/ansible-sign/.venv/bin/sigstore", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mcostant/Documents/Repositories/RedHat/Ansible_Sigstore/ansible-sign/.venv/lib64/python3.11/site-packages/sigstore/_cli.py", line 555, in main
    _verify_identity(args)
  File "/home/mcostant/Documents/Repositories/RedHat/Ansible_Sigstore/ansible-sign/.venv/lib64/python3.11/site-packages/sigstore/_cli.py", line 921, in _verify_identity
    verifier, files_with_materials = _collect_verification_state(args)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcostant/Documents/Repositories/RedHat/Ansible_Sigstore/ansible-sign/.venv/lib64/python3.11/site-packages/sigstore/_cli.py", line 801, in _collect_verification_state
    certificate_chain = load_pem_x509_certificates(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcostant/Documents/Repositories/RedHat/Ansible_Sigstore/ansible-sign/.venv/lib64/python3.11/site-packages/cryptography/x509/base.py", line 587, in load_pem_x509_certificates
    return rust_x509.load_pem_x509_certificates(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'data': 'str' object cannot be converted to 'PyBytes'
```

According to the [`cryptography` docs](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.load_pem_x509_certificates), the `cryptography.x509.load_pem_x509_certificates` method expected `bytes` data and not `str`. Fixing the `argparse.FileType` for the `--certificate-chain` option to `rb` solved the issue.

**Version**

`2.0.0`

**Comment by mayaCostantini** [comment]
Fix proposed in https://github.com/sigstore/sigstore-python/pull/796
