### ISSUE TITLE
OAuth flow: intermittent 400 errors

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#96]
**Description**

When running `sigstore` locally with the OAuth OIDC flow, I occasionally get HTTP 400s. Happens with both `sigstore.dev` and `sigstage.dev` as the instance. The error code indicates that it's almost certainly a payload construction error on our side, possibly due to raciness when setting up the local HTTP listener.

Example invocation:

```console
$ sigstore sign README.md
```

Example traceback:

```
BUG:urllib3.connectionpool:https://oauth2.sigstage.dev:443 "POST /auth/token HTTP/1.1" 400 70
Traceback (most recent call last):
  File "/Users/william/devel/sigstore-python/sigstore/_internal/oidc/oauth.py", line 193, in get_identity_token
    resp.raise_for_status()
  File "/Users/william/devel/sigstore-python/env/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://oauth2.sigstage.dev/auth/token

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/william/devel/sigstore-python/env/bin/sigstore", line 8, in <module>
    sys.exit(main())
  File "/Users/william/devel/sigstore-python/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/william/devel/sigstore-python/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/william/devel/sigstore-python/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/william/devel/sigstore-python/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/william/devel/sigstore-python/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/william/devel/sigstore-python/sigstore/_cli.py", line 110, in _sign
    identity_token = get_identity_token(
  File "/Users/william/devel/sigstore-python/sigstore/_internal/oidc/oauth.py", line 195, in get_identity_token
    raise IdentityError from http_error
sigstore._internal.oidc.IdentityError
```

**Comment by woodruffw** [comment]
@di also reports a 401 with the staging instance, which is possibly not our fault:

```
$ python -m sigstore sign --oidc-disable-ambient-providers hi.txt
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.sigstore.dev:443
DEBUG:urllib3.connectionpool:https://oauth2.sigstore.dev:443 "GET /auth/.well-known/openid-configuration HTTP/1.1" 200 1140
Go to the following link in a browser:

    https://oauth2.sigstore.dev/auth/auth?response_type=code&client_id=sigstore&client_secret=&scope=openid+email&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&code_challenge=zIIMEn9r4o0egPe2RBMj1nRpdXECY06UI7W8gST9Se8&code_challenge_method=S256&state=5b93a96c-6686-4932-a779-36b91245839c&nonce=e78940cc-f6a8-4fe3-a8b4-169c419f2728
Enter verification code: zq3lgnh6iwc6ocm3u727sapar
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.sigstore.dev:443
DEBUG:urllib3.connectionpool:https://oauth2.sigstore.dev:443 "POST /auth/token HTTP/1.1" 200 2044
DEBUG:sigstore._sign:Using payload from: hi.txt
DEBUG:sigstore._sign:Generating ephemeral keys...
DEBUG:sigstore._sign:Retrieving signed certificate...
DEBUG:sigstore._internal.fulcio.client:Fulcio client using URL: https://fulcio.sigstage.dev
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): fulcio.sigstage.dev:443
DEBUG:urllib3.connectionpool:https://fulcio.sigstage.dev:443 "POST /api/v1/signingCert HTTP/1.1" 401 101
Traceback (most recent call last):
  File "/home/di/git/sigstore/sigstore-python/sigstore/_internal/fulcio/client.py", line 222, in post
    resp.raise_for_status()
  File "/home/di/.pyenv/versions/3.9.10/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fulcio.sigstage.dev/api/v1/signingCert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/di/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/di/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/di/git/sigstore/sigstore-python/sigstore/__main__.py", line 22, in <module>
    main()
  File "/home/di/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/di/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/di/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/di/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/di/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/di/git/sigstore/sigstore-python/sigstore/_cli.py", line 121, in _sign
    result = sign(
  File "/home/di/git/sigstore/sigstore-python/sigstore/_sign.py", line 102, in sign
    certificate_response = fulcio.signing_cert.post(certificate_request, identity_token)
  File "/home/di/git/sigstore/sigstore-python/sigstore/_internal/fulcio/client.py", line 226, in post
    raise FulcioClientError(text["message"]) from http_error
sigstore._internal.fulcio.client.FulcioClientError: There was an error processing the credentials for this request
```

In any case, we should attempt to more gracefully handle these errors (as well as root cause them).

**Comment by di** [comment]
I think that last one is due to accidentally mixing `sigstore.dev` and `sigstage.dev` -- we should do a better job of propagating these changes through all our defaults.

**Comment by tetsuo-cpp** [comment]
Looking into this now.

**Comment by kushaldas** [comment]
I installed from git `ac11c48b010129a09afc30e6aea650df24f133a2` on main branch today. I am still getting the same error.

**Comment by woodruffw** [comment]
Thanks for the report. Are you able to reproduce it? If so, could you add `SIGSTORE_LOGLEVEL=debug` and post the logs here?

**Comment by woodruffw** [comment]
Reopening for the time being, since we're likely not fully resolved.

**Comment by kushaldas** [comment]
> Thanks for the report. Are you able to reproduce it? If so, could you add `SIGSTORE_LOGLEVEL=debug` and post the logs here?

I am getting the same error every time.

The debug log:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.sigstore.dev:443
DEBUG:urllib3.connectionpool:https://oauth2.sigstore.dev:443 "POST /auth/token HTTP/1.1" 400 70
Traceback (most recent call last):
  File "/home/kdas/code/sigstore-python/sigstore/_internal/oidc/oauth.py", line 203, in get_identity_token
    resp.raise_for_status()
  File "/home/kdas/code/sigstore-python/.venv/lib64/python3.10/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://oauth2.sigstore.dev/auth/token

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kdas/code/sigstore-python/sigstore/__main__.py", line 22, in <module>
    main()
  File "/home/kdas/code/sigstore-python/sigstore/_cli.py", line 254, in main
    _sign(args)
  File "/home/kdas/code/sigstore-python/sigstore/_cli.py", line 333, in _sign
    args.identity_token = get_identity_token(
  File "/home/kdas/code/sigstore-python/sigstore/_internal/oidc/oauth.py", line 205, in get_identity_token
    raise IdentityError from http_error
sigstore._internal.oidc.IdentityError

```

**Comment by woodruffw** [comment]
Not a super helpful debug log, but that's our fault and not yours 😅.

Thanks again. I'll take a look into this today and see if I can repro. 

Out of curiosity: which IdP did you select in the OAuth flow? Does it happen with all of them?

**Comment by woodruffw** [comment]
Also: what browser did you do the OAuth flow with, and which version?

**Comment by woodruffw** [comment]
Working on this in #136. I was unable to repro with Chrome (102), Firefox (98), or Safari (15.5) all on macOS, but I'll keep experimenting.

**Comment by kushaldas** [comment]
I am using Firefox 101.0.1 and using Github as IDP.

**Comment by kushaldas** [comment]
Also tried with `Chrome Version 102.0.5005.115 (Official Build) (64-bit)` and Google as IDP, same error.

**Comment by di** [comment]
@kushaldas Are you getting the "Your browser will now be opened to" prompt or the "Go to the following link in a browser" prompt?

**Comment by kushaldas** [comment]
> @kushaldas Are you getting the "Your browser will now be opened to" prompt or the "Go to the following link in a browser" prompt?

I am getting `Your browser will now be opened to:` prompt.

**Comment by woodruffw** [comment]
@kushaldas Could you try with the logging changes on #136? I'm wondering if your browser is making additional requests that are confusing the flow.

**Comment by woodruffw** [comment]
I'll also try reproducing in a Fedora VM.

**Comment by woodruffw** [comment]
The payloads between macOS (successful) and Fedora (failure) look identical, modulo the parts that we expect to vary (the port on the local server, the `code` and the `code_verifier`). So maybe it's something about *how* we're sending the payload?

**Comment by woodruffw** [comment]
I believe #136 (now merged) should resolve this. But I'll wait for @kushaldas to confirm before closing.

**Comment by woodruffw** [comment]
Fantastic. Thanks a ton for helping us debug.

**Comment by di** [comment]
Yep, thank you @kushaldas! Also would love to hear about what you're hoping to use this for, feel free to drop us a line in Slack.
